name: msrv-badge

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  # install-cargo-msrv:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install cargo-msrv
  #       run: cargo install cargo-msrv --git https://github.com/foresterre/cargo-msrv.git --branch main
  create-msrv-badge:
    # needs: install-cargo-msrv
    runs-on: ubuntu-latest
    container: foresterre/cargo-msrv
    strategy:
      matrix:
        crates: [yea_fen, yea_fen_uci, yea_fen_gui]
      fail-fast: false
    steps:
      
      - uses: actions/checkout@v3
      - name: Get MSRV
        id: get-msrv
        run: |
          echo "msrv=$(cargo msrv --manifest-path ${{ matrix.crates }}/Cargo.toml)" >> $GITHUB_ENV

      - name: Create Badge
        run: curl https://img.shields.io/badge/minimum%20rust%20version-${{ env.msrv }}-blue.svg > resources/${{ matrix.crates }}_msrv.svg
      - name: Commit Badge
        # If there are no changes to the badge this would error out. But it
        # isn't a problem if there were no changes, so errors are allowed.
        continue-on-error: true
        run: |
          git pull
          git add resources/${{ matrix.crates }}_msrv.svg
          git add ${{ matrix.crates }}/Cargo.toml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Update MSRV badge [Skip CI]"
          git push